app_code: te_saas
app_name: 模板测试
author: morton
category: 运维工具
container:
    memory: 1024
!!python/unicode 'date': '2021-2-18 10:05:00'
desktop:
  width: 1280
  height: 720
  is_max: True
introduction: 响应式布局前端
is_use_celery: False
language: python
version: 3.6.28
date: 2021-2-18 10:05:13
